# Generated by Django 4.1.7 on 2023-02-28 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_options_post_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='posts',
        ),
    ]
